### PR TITLE
Added all device deployment targets

### LINKED ISSUE #4: Add tvOS support
Add support for tvOS in the pod spec

### PR DESCRIPTION
**Pull request by joeblau**
Fixes #4 Add tvOS support

### CODE REVIEW

**Comment by colinta** [comment]
Awesome! 💯 Thanks!

**Comment by colinta** [comment]
I don't know why Travis failed on this change, but locally it's all good.

Actually, locally I couldn't get specs to run - Xcode 7.3 frustration, I think, but I'm gonna convert these specs to XCTestCase so that we don't have to install Quick & Nimble.

**Comment by joeblau** [comment]
There is bundle being included.  I didn't run the tests locally, but I'm not sure why the bundle in the demo in the app is included in the cocoapod repo?

**Comment by colinta** [comment]
That's for localization.  I'll admit, though, I was flying blind there, so if it looks like I messed it up, please let us know!

**Comment by joeblau** [comment]
Okay, I can take a look at it when I get home.  Shouldn't be to hard to fix.

**Pull request merged**
